/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2018-09-16 15:11:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fisheryAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/fishbang/tomcatwork/wtpwebapps/team5/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1536116268592L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- javascript -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("#mains{\r\n");
      out.write("border:1px solid tomato;\r\n");
      out.write("height:8000px;\r\n");
      out.write("}\r\n");
      out.write("#feedBoard{\r\n");
      out.write("\r\n");
      out.write("width:1000px;\r\n");
      out.write("height:3000px;\r\n");
      out.write("margin-right:10px;\r\n");
      out.write("float:left;\r\n");
      out.write("display:block;\r\n");
      out.write("}\r\n");
      out.write("#side{\r\n");
      out.write("\r\n");
      out.write("width:355px;\r\n");
      out.write("height:3000px;\r\n");
      out.write("margin-left:1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" .line{\r\n");
      out.write(" background-color:#FCFCFC;\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  width: 900px;\r\n");
      out.write("        height: 2800px;\r\n");
      out.write("      border-bottom: 2px solid #72655F;\r\n");
      out.write("      border-right: 2px solid #72655F;\r\n");
      out.write("      border-left: 2px solid #72655F;\r\n");
      out.write("       margin-top: -20px;\r\n");
      out.write("        margin-right: 5%;\r\n");
      out.write("        margin-left: 5%;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(".fishinfolayout{\r\n");
      out.write("border-radius:10px;\r\n");
      out.write("background-color : white;\r\n");
      out.write("margin-top : 70px;\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("width: 200px;\r\n");
      out.write("height: 230px;\r\n");
      out.write(" list-style: none;/* <!--li블록의 점모양 없애줌--> */\r\n");
      out.write(" float: left; /*li블록 가로로 나열해줌  */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".fishinfoline{\r\n");
      out.write("opacity: 0.4;\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("\twidth: 190px;\r\n");
      out.write("\theight: 229px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("/*투명도 조절  */\r\n");
      out.write(".fishinfoline:hover{\r\n");
      out.write("opacity: 1;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fishimg{\r\n");
      out.write("\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("width : 188px;\r\n");
      out.write("height : 150px;\r\n");
      out.write("}\r\n");
      out.write(".fishname1{\r\n");
      out.write("font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("color: gray;\r\n");
      out.write("\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("width: 188px;\r\n");
      out.write("height: 40px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fishviewcnt{\r\n");
      out.write("\r\n");
      out.write("font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("color: gray;\r\n");
      out.write("\r\n");
      out.write("text-align: center;\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("width: 188px;\r\n");
      out.write("height: 20px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".just{\r\n");
      out.write("margin-top : 8.7px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ul.tabs {\r\n");
      out.write("\r\n");
      out.write("width: 803px;\r\n");
      out.write("height: 80px;\r\n");
      out.write("margin-left : 50px;\r\n");
      out.write("margin-bottom : -10px;\r\n");
      out.write("list-style: none;\r\n");
      out.write("overflow: hidden;\r\n");
      out.write("padding: 0;\r\n");
      out.write("}\r\n");
      out.write("ul.tabs li {\r\n");
      out.write("float: left;\r\n");
      out.write("width: 190px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("ul.tabs li a {\r\n");
      out.write("position: relative;\r\n");
      out.write("display: block;\r\n");
      out.write("height: 70px;\r\n");
      out.write("margin-top: 40px;\r\n");
      out.write("padding: 10px 0 0 0;\r\n");
      out.write("font-size: 18px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("color: #444;\r\n");
      out.write("background: #FCFCFC;\r\n");
      out.write("-webkit-box-shadow: 8px 12px 25px 2px rgba(0,0,0,0.4);\r\n");
      out.write("-moz-box-shadow: 8px 12px 25px 2px rgba(0,0,0,0.4);\r\n");
      out.write("-box-shadow: 8px 12px 25px 2px rgba(0,0,0,0.4);\r\n");
      out.write("border: 0px solid #000;\r\n");
      out.write("-webkit-transition: padding 0.2s ease, margin 0.2s ease;\r\n");
      out.write("-moz-transition: padding 0.2s ease, margin 0.2s ease;\r\n");
      out.write("-ms-transition: padding 0.2s ease, margin 0.2s ease;\r\n");
      out.write("-o-transition: padding 0.2s ease, margin 0.2s ease;\r\n");
      out.write("transition: padding 0.2s ease, margin 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tabs li:first-child a {\r\n");
      out.write("  z-index: 5\r\n");
      out.write("-webkit-border-top-left-radius: 8px;\r\n");
      out.write("-moz-border-radius-topleft: 8px;\r\n");
      out.write("border-top-left-radius: 8px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.tabs li a:hover {\r\n");
      out.write("  margin: 35px 0 0 0;\r\n");
      out.write("  padding: 10px 0 5px 0;\r\n");
      out.write("}\r\n");
      out.write("ul.tabs li a.activeTab {\r\n");
      out.write("margin: 30px 0 0 0;\r\n");
      out.write("padding: 10px 0 10px 0;\r\n");
      out.write("color: #444;\r\n");
      out.write("background: #FCFCFC;\r\n");
      out.write("border-top: 2px solid #72655F;\r\n");
      out.write("border-right: 2px solid #72655F;\r\n");
      out.write("border-left: 2px solid #72655F;\r\n");
      out.write("z-index: 6;\r\n");
      out.write("outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <nav class=\"navbar navbar-inverse navbar-global navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">fishbang</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"collapse navbar-collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-user navbar-right\">\r\n");
      out.write("            <li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span> 로그인시 id 표기 </a></li>\r\n");
      out.write("            <li><a href=\"#about\"><span class=\"glyphicon glyphicon-log-in\"></span> login</a></li>\r\n");
      out.write("            <li><a href=\"#about\"><span class=\"glyphicon glyphicon-log-out\"></span> logout</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<nav class=\"navbar-primary\">\r\n");
      out.write("  <a href=\"#\" class=\"btn-expand-collapse\"><span class=\"glyphicon glyphicon-menu-left\"></span></a>\r\n");
      out.write("  <ul class=\"navbar-primary-menu\">\r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"#\"><span class=\"glyphicon glyphicon-book\"></span><span class=\"nav-label\">내어장보기(로그인시)</span></a>\r\n");
      out.write("      <a href=\"#\"><span class=\"glyphicon glyphicon-book\"></span><span class=\"nav-label\">어류도감(비로그인)</span></a>\r\n");
      out.write("      <a href=\"#\"><span class=\"glyphicon glyphicon-tint\"></span><span class=\"nav-label\">날씨,물때정보(option)</span></a>\r\n");
      out.write("      <a href=\"#\"><span class=\"glyphicon glyphicon-thumbs-up\"></span><span class=\"nav-label\">조과랭킹</span></a>\r\n");
      out.write("      <a href=\"#\"><span class=\"glyphicon glyphicon-question-sign\"></span><span class=\"nav-label\">고객센터(option)</span></a>\r\n");
      out.write("\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"main-content\">\t\r\n");
      out.write("\r\n");
      out.write(" <div id=\"mains\">\r\n");
      out.write("  \t<div id=\"feedBoard\">\r\n");
      out.write("  \t\r\n");
      out.write(" <ul class=\"tabs group\">\r\n");
      out.write("    <li>\r\n");
      out.write("           <a class=\"tabOne switch activeTab\" href=\"#\">내 어장</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("           <a class=\"tabTwo switch\" href=\"#\">잡은 바다고기</a>\r\n");
      out.write("    </li>\r\n");
      out.write("     <li>\r\n");
      out.write("           <a class=\"tabTwo switch\" href=\"#\">잡은 민물고기</a>\r\n");
      out.write("    </li>\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \t<div class = \"line\">\r\n");
      out.write("  \t\r\n");
      out.write("  \r\n");
      out.write("  \t\r\n");
      out.write("  \t<div class =\"contentlineass\">\r\n");
      out.write("    <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write("   <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write("   <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write("   <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write("   <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write("   <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write("   <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write("   <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write(" \r\n");
      out.write("   <ul class = \"v\">\r\n");
      out.write("  \r\n");
      out.write("<li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" <li class =\"fishinfolayout\">\r\n");
      out.write("  \t<div class = \"fishinfoline\">\r\n");
      out.write("  \t\r\n");
      out.write("  \t\t<div class = \"fishimg\">\r\n");
      out.write("  \t\t<img src = \"/team5/src/main/resources/godonga1.png\" width = \"185\" height = \"150\" alt = \"이미지파일이어딨지?\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t<div class = \"just\">\r\n");
      out.write("  \t\t\t\t\t<p class = \"fishname1\">고등어<br>godonga</p>\r\n");
      out.write("  \r\n");
      out.write("  \t\t\t\t\t<p class = \"fishviewcnt\">물고기 길이, 잡은 마릿수</p>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write(" </li>\r\n");
      out.write(" \r\n");
      out.write(" </ul>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<div id=\"side\"> </div>\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$('.btn-expand-collapse').click(function(e) {\r\n");
      out.write("\t$('.navbar-primary').toggleClass('collapsed');\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /jsp/fisheryAll.jsp(8,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/newmain.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
