/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2018-09-16 15:14:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newmain_005fboard_005ffeeds_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/fishbang/tomcatwork/wtpwebapps/team5/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1536116268592L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<!-- /* Facebook Feed Style*/  -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- javascript -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- fontawesone 로고 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.3.1/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Main Board Feeds</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* <!-- Section Divider CSS --> */\r\n");
      out.write("#mains {\r\n");
      out.write("\tborder: 1px solid tomato;\r\n");
      out.write("\theight: 8000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#feedBoard {\r\n");
      out.write("\tborder: 1px solid blue;\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\theight: 3000px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#side {\r\n");
      out.write("\tborder: 1px solid yellow;\r\n");
      out.write("\twidth: 355px;\r\n");
      out.write("\theight: 3000px;\r\n");
      out.write("\tmargin-left: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a, div {\r\n");
      out.write("\tfont-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* <!-- Write Post CSS --> */\r\n");
      out.write("input[type=\"file\"] {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("\tpadding: .5em 1em;\r\n");
      out.write("\tbackground-color: transparent;\r\n");
      out.write("\tcolor: #6b7270;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post {\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tmin-height: 100px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tborder: 1px solid #eaeaea;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tbox-shadow: 0 1px 2px 1px rgba(130, 130, 130, 0.1);\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post__header {\r\n");
      out.write("\tpadding: .2em .5em;\r\n");
      out.write("\tbackground-color: #eaeaea;\r\n");
      out.write("\tcolor: #3f5563;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post__title {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post__content {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post__textarea {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tpadding: .5em;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tresize: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post__textarea:focus {\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post__fishcatch {\r\n");
      out.write("\tpadding: .5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post___input {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tpadding: .2em .5em;\r\n");
      out.write("\tborder: 1px solid #eaeaea;\r\n");
      out.write("\tborder-radius: 1.5em;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("i#unit {\r\n");
      out.write("\tmargin-left: -10px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#letgo {\r\n");
      out.write("\tmargin-right: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post___input.widget-post--date, .widget-post___input.search--method\r\n");
      out.write("\t{\r\n");
      out.write("\twidth: 140px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post-actions__label {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".widget-post__actions {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: .5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post--actions {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tpadding: .5em;\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("\tcolor: #a2a6a7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post-actions__attachments {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".attachments--btn {\r\n");
      out.write("\tbackground-color: #eaeaea;\r\n");
      out.write("\tcolor: #007582;\r\n");
      out.write("\tborder-radius: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post-actions__widget {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 38%;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post-actions__publish {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\tbackground-color: #008391;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tborder-radius: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroller::-webkit-scrollbar {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".is--hidden {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* * SR * */\r\n");
      out.write(".sr-only {\r\n");
      out.write("\twidth: 1px;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tclip: rect(1px, 1px, 1px, 1px);\r\n");
      out.write("\t-webkit-clip-path: inset(50%);\r\n");
      out.write("\tclip-path: inset(50%);\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* *  Placeholder contrast * */\r\n");
      out.write("::-webkit-input-placeholder {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("::-moz-placeholder {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(":-ms-input-placeholder {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(":-moz-placeholder {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* <!-- Feeds CSS --> */\r\n");
      out.write(".feed {\r\n");
      out.write("\tborder: 1px #f1f1f1 solid;\r\n");
      out.write("\tpadding: 15px 15px 0 15px;\r\n");
      out.write("\tmax-height: 600px;\r\n");
      out.write("\tmax-width: auto;\r\n");
      out.write("\t/* overflow-y:scroll */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".feed_share {\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tfont-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".feed_share a {\r\n");
      out.write("\tcolor: #333\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("small {\r\n");
      out.write("\tcolor: #d0d0d0;\r\n");
      out.write("\tmargin-bottom: 15px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa {\r\n");
      out.write("\tcolor: #afb4bd\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".feed_comment {\r\n");
      out.write("\tbackground: #f9fafb;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tborder-top: 1px #f1f1f1 solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td#table-header {\r\n");
      out.write("\ttext-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-global navbar-fixed-top\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\tdata-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-controls=\"navbar\">\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"><span><i\r\n");
      out.write("\t\t\t\tclass=\"fas fa-fish fa-1x\"></i></span>&nbsp;fishbang</a>\r\n");
      out.write("\t\t<!-- 현재 페이지 새로 고침  -->\r\n");
      out.write("\t\t<!-- 현재 페이지 새로 고침  -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"navbar\" class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t<ul class=\"nav navbar-nav navbar-user navbar-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 비로그인 시  -->\r\n");
      out.write("\t\t\t<li><a href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-plus\"></span> signup</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> login</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 로그인 시  -->\r\n");
      out.write("\t\t\t<li><a href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></span> fishbang@fish.bang</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span> logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--/.nav-collapse -->\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<nav class=\"navbar-primary\"> <a href=\"#\"\r\n");
      out.write("\tclass=\"btn-expand-collapse\"><span\r\n");
      out.write("\tclass=\"glyphicon glyphicon-menu-left\"></span></a>\r\n");
      out.write("<ul class=\"navbar-primary-menu\">\r\n");
      out.write("\t<li><a href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"><span\r\n");
      out.write("\t\t\tclass=\"glyphicon glyphicon-book\"></span><span class=\"nav-label\">내어장보기(로그인시)</span></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"><span\r\n");
      out.write("\t\t\tclass=\"glyphicon glyphicon-book\"></span><span class=\"nav-label\">어류도감(비로그인)</span></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"#\"><span class=\"glyphicon glyphicon-tint\"></span><span\r\n");
      out.write("\t\t\tclass=\"nav-label\">날씨,물때정보(option)</span></a> <a\r\n");
      out.write("\t\thref=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"><span\r\n");
      out.write("\t\t\tclass=\"glyphicon glyphicon-thumbs-up\"></span><span class=\"nav-label\">조과랭킹</span></a>\r\n");
      out.write("\t\t<a href=\"#\"><span class=\"glyphicon glyphicon-question-sign\"></span><span\r\n");
      out.write("\t\t\tclass=\"nav-label\">고객센터(option)</span></a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main-Content 각자의 페이지 작성  -->\r\n");
      out.write("\t<div class=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"mains\">\r\n");
      out.write("\t\t\t<div id=\"feedBoard\">\r\n");
      out.write("\t\t\t\t<div class=\"widget-post\" aria-labelledby=\"post-header-title\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget-post__header\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"widget-post__title\" id=\"post-header-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-pencil\" aria-hidden=\"true\"></i> 나의 조과 올리기\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form id=\"widget-form\" class=\"widget-post__form\" name=\"form\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"post widget\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-post__actions post--actions\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-actions__attachments\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn post-actions__fish attachments--btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"stock-options\" aria-haspopup=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-usd\" aria-hidden=\"true\"></i>조과 정보작성\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-actions__widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn post-actions__addfish attachments--btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"addfish\" class=\"post-actions__label\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"\" aria-hidden=\"true\"></i>조과추가+</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn post-actions__publish\">조과등록</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-post__fishcatch \" id=\"fish-kind\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"date\">출조날짜:</label> <input type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"widget-post___input widget-post--date\" id=\"date\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"search\">출조지역:</label> <input type=\"search\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"예)거제도\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"widget-post___input widget-post--search search--location\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"search\"> <label for=\"search\">낚시방법:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"search\" placeholder=\"예)방파제낚시\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"widget-post___input widget-post--search search--method\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"search\"> <br> <label for=\"search\">어종:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"search\" placeholder=\"예)놀래미\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"widget-post___input widget-post--search search--fish\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"search\"> <label for=\"fish-length\">전장:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"number\" class=\"widget-post___input widget-post--length\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"fish-length\" placeholder=\"길이(전장)\"><i id=\"unit\">cm</i>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"fish-weight\">무게:</label> <input type=\"number\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"widget-post___input widget-post--weight\" id=\"fish-weight\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"무게(체중)\"><i id=\"unit\">kg</i> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tfor=\"letgo\">방생</label> <input type=\"checkbox\" id=\"letgo\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn post-actions__upload attachments--btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"upload-image\" class=\"post-actions__label\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-camera\" aria-hidden=\"true\"></i>인증사진 등록</label>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"upload-image\" accept=\"image/*\" multiple>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-post__content\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"post-content\" class=\"sr-only\">자유글 또는 조황에 대한\r\n");
      out.write("\t\t\t\t\t\t\t\t설명을 작성해주세요.</label>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"post\" id=\"post-content\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"widget-post__textarea scroller\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"(#태그 사용가능)자유글 또는 조황에 대한 설명을 작성해주세요.\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"fb\" id=\"download\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"img fileinput-preview\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"catch1.png\" width=\"40\" height=\"40\" id=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong><a href=\"#\"><span class=\"text-name\">다잡아</span></a></strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pull-right btn btn-xs btn-following\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-check\" aria-hidden=\"true\" style=\"color: white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t공식</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"text-when\">어제 at 4:42am</span> ·<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://social-prank.foxsash.com/assets/images/facebook/icon_public.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth=\"16\" height=\"16\" id=\"visiblefor-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-message\">\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"table-header\">출조날짜: &nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>2018.09.15 (금)&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"table-header\">출조지역: &nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>거제도 어느 방파제 &nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"table-header\">낚시방법: &nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>방파제 낚시</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"table-header\">어종(바다): &nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>놀래미 &nbsp; &nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"table-header\">전장: &nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>20cm &nbsp; &nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"table-header\">무게: &nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>(미입력)kg &nbsp; &nbsp;&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><img src=\"gamsung.jpg\" width=300px></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"txtbottom\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"text-liketext\">대박</a> · <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text-commenttext\">댓글</a> · <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text-sharetext\">공유</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post_likes\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"http://social-prank.foxsash.com/assets/images/facebook/facebook_like_thumb.png\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><span class=\"text-likes\">420 명이 대박을</span></a> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"text-likethistext\">을 눌렀어요</span> .\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post_shares\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"shares\"></i> <a href=\"#\"><span class=\"text-shares\">42\r\n");
      out.write("\t\t\t\t\t\t\t\t공유됨</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"comments\" id=\"comments\">\r\n");
      out.write("\t\t\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"UFIRow  UFILastComment UFILastCommentComponent UFILastComponent UFIComment display UFIComponent UFIUnseenItem\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"_ohe lfloat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"https://www.facebook.com/nivaldo.silva.7923030?fref=ufi\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img _8o _8s UFIImageBlockImage\" tabindex=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-hidden=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$left.0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-owns=\"js_m\" aria-haspopup=\"true\" aria-describedby=\"js_n\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"js_o\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfa1/v/t1.0-1/p32x32/1507769_1386250438296116_2074273629_n.jpg?oh=fdbe28f85fc29943c38c2e00bc85c9e7&amp;oe=55F799C7&amp;__gda__=1445479768_f45df0b9dbfbfd416615a102489ac39c\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img UFIActorImage _54ru\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$left.0.0\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"UFIImageBlockContent _42ef clearfix\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"_ohf rfloat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"UFICommentCloseButtonFake _50zy _50-0 _50z- _5upp _42ft\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"-1\" type=\"button\" title=\"Remover\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$right.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$right.0.1\">Remover</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"UFICommentContentBlock\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"UFICommentContent\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.0\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-ft=\"{&quot;tn&quot;:&quot;;&quot;}\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\" UFICommentActorName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-hovercard=\"/ajax/hovercard/hovercard.php?id=100007335194048&amp;extragetparams=%7B%22hc_location%22%3A%22ufi%22%7D\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdir=\"ltr\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"https://www.facebook.com/nivaldo.silva.7923030?fref=ufi\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.0.0\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.0.0.0\">Nivaldo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tSilva</span></a></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.1\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.1.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</span><span data-ft=\"{&quot;tn&quot;:&quot;K&quot;}\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.1.$comment-body\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"UFICommentBody\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.1.$comment-body.0\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.1.$comment-body.0.$end:0:$text0:0\">Delicia\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tde mulher cc</span></span></span></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.0.6\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"fsm fwn fcg UFICommentActions\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.3.$metadata:0\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"uiLinkSubtle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"/groups/406892826118728/permalink/596675990473743/?comment_id=599044600236882&amp;offset=0&amp;total_comments=3&amp;comment_tracking=%7B%22tn%22%3A%22R%22%7D\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-ft=\"{&quot;tn&quot;:&quot;N&quot;}\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.3.$metadata:0.$timestamp-message\"><abbr\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"livetimestamp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttitle=\"Quarta, 17 de junho de 2015 às 04:43\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-utime=\"1434526981\" data-shorten=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.3.$metadata:0.$timestamp-message.0\">1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\th</abbr></a></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.3.$likeToggle:0:$MIDDOT:0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t· </span><a class=\"UFILikeLink\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-ft=\"{&quot;tn&quot;:&quot;>&quot;}\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\trole=\"button\" title=\"Curtir este comentário\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.3.$likeToggle:0:$action:0\">Curtir</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"UFICommentCloseButton _50zy _50-0 _50z- _5upp _42ft\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"#\" aria-label=\"Ocultar\" data-hover=\"tooltip\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tooltip-alignh=\"center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-reactid=\".1.1:4:1:$comment596675990473743_599044600236882:0.0.$right.0.$left.0.4\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post_write_comment\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"https://graph.facebook.com/davidaugustus42/picture\"\r\n");
      out.write("\t\t\t\t\t\t\t\twidth=\"32\" height=\"32\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"txt\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text_block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"comment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-left text-wrcommenttext\">댓글달기</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-right text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"http://social-prank.foxsash.com/assets/images/facebook/fot_ico.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fot_ico\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"http://social-prank.foxsash.com/assets/images/facebook/smile_ico.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"smile_ico\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--  다른 스타일의 포스트 feeds -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"feed\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> <img class=\"media-object img-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"http://www.caclubindia.com/img/blank.gif\" width=\"50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--media left-->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pull-right btn btn-xs btn-following\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-check\" aria-hidden=\"true\" style=\"color: white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t공식</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"media-heading\">은비까비</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<small>Posted a new Article</small><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"http://www.caclubindia.com/img/preview/paidnfree/Img_22_10.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"float: left; width: 50%; margin-right: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>This is Photoshop's version of Lorem Ipsum. Proin gravida\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbibendum.si elit consequat ipsum, nec sagittis sem nibh id\r\n");
      out.write("\t\t\t\t\t\t\t\t\telit. Duis sed odio sit amet nibh vulputate cursus as.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"feed_share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"\"><span><i class=\"fa fa-comments\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> Comment</a>&nbsp;&nbsp; <a href=\"\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-thumbs-up\" aria-hidden=\"true\"></i> Like <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"badge\">12</span> </a> &nbsp;&nbsp; <a href=\"\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-share\" aria-hidden=\"true\"></i> Share</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--media body-->\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> <img class=\"media-object img-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"http://www.caclubindia.com/img/blank.gif\" width=\"50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pull-right btn btn-xs btn-following\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-check\" aria-hidden=\"true\" style=\"color: white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t공식</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"media-heading\">다잡어</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<small>Commented in Articles</small><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>This is Photoshop's version of Lorem Ipsum. Proin gravida\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbibendum.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"feed_share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"\"><span> <a href=\"\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-thumbs-up\" aria-hidden=\"true\"></i> Like</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-comments\" aria-hidden=\"true\"></i> Comment</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"\"><i class=\"fa fa-share\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tShare</a>/span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--media body-->\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> <img class=\"media-object img-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"http://www.caclubindia.com/img/avatars/my_avatars/662313.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pull-right btn btn-xs btn-follow\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-plus\" aria-hidden=\"true\"></i> 비공식</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"media-heading\">대물킹</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<small>Commented in Articles</small><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>This is Photoshop's version of Lorem Ipsum. Proin gravida\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbibendum.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"feed_share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"\"><span><i class=\"fa fa-comments\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> Comment</a>&nbsp;&nbsp; <a href=\"\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-thumbs-up\" aria-hidden=\"true\"></i> Like</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&nbsp;&nbsp; <a href=\"\"><i class=\"fa fa-share\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> Share</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--media body-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!--media body-->\r\n");
      out.write("\t\t\t\t\t\t<!--comment-->\r\n");
      out.write("\t\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"feed_comment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" placeholder=\"Write a comment...\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary-outline\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\" style=\"color: white\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pre_comment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"> <img class=\"media-object img-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"http://www.caclubindia.com/img/blank.gif\" width=\"40px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small>Commented in Articles</small><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Nice Post .....</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Main-Content 각자의 Side 페이지 작성  -->\r\n");
      out.write("\t\t\t<div id=\"side\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('.btn-expand-collapse').click(function(e) {\r\n");
      out.write("\t\t\t$('.navbar-primary').toggleClass('collapsed');\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar fishBtn = document.querySelector('.post-actions__fish');\r\n");
      out.write("\t\tvar postFishCatch = document.querySelector('.widget-post__fishcatch');\r\n");
      out.write("\t\tvar searchLocation = document.querySelector('.search--location');\r\n");
      out.write("\r\n");
      out.write("\t\tvar uploadBtn = document.querySelector('.post-actions__upload');\r\n");
      out.write("\t\tvar uploadLabel = document.querySelector('.post-actions__label');\r\n");
      out.write("\r\n");
      out.write("\t\tvar a11yRoleExpanded = function(targetElm, clickElm) {\r\n");
      out.write("\t\t\tif (targetElm.classList.contains('is--hidden')) {\r\n");
      out.write("\t\t\t\tclickElm.setAttribute('aria-expanded', 'false');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tclickElm.setAttribute('aria-expanded', 'true');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar fakeUploadClick = function(e) {\r\n");
      out.write("\t\t\tvar keyboardNum = e.which;\r\n");
      out.write("\t\t\tif (keyboardNum === 13 || keyboardNum === 32) {\r\n");
      out.write("\t\t\t\tuploadLabel.click();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tfishBtn.setAttribute('aria-expanded', 'true');\r\n");
      out.write("\t\tfishBtn.addEventListener('click', function() {\r\n");
      out.write("\t\t\tpostFishCatch.classList.toggle('is--hidden');\r\n");
      out.write("\t\t\tsearchLocation.focus();\r\n");
      out.write("\t\t\ta11yRoleExpanded(postFishCatch, fishBtn);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tuploadBtn.addEventListener('keydown', fakeUploadClick);\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /jsp/newmain_board_feeds.jsp(8,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/newmain.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /jsp/newmain_board_feeds.jsp(11,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/css/fb-style-feeds-element.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /jsp/newmain_board_feeds.jsp(264,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/jsp/newmain.jsp");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /jsp/newmain_board_feeds.jsp(273,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/jsp/firstpage.jsp");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /jsp/newmain_board_feeds.jsp(275,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/jsp/firstpage.jsp");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /jsp/newmain_board_feeds.jsp(279,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/jsp/updateuserpage.jsp");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /jsp/newmain_board_feeds.jsp(281,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/jsp/newmain.jsp");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /jsp/newmain_board_feeds.jsp(292,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/jsp/fisheryAll.jsp");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /jsp/newmain_board_feeds.jsp(297,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/jsp/fishDictAll.jsp");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /jsp/newmain_board_feeds.jsp(304,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/jsp/rankingMain.jsp");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }
}
