/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2018-09-18 14:55:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class projectMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/fishbang/tomcatwork/wtpwebapps/team5/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1536116268592L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Shadows+Into+Light\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- google font -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\r\n");
      out.write("<!-- background script -->\r\n");
      out.write("\r\n");
      out.write("<title>TestMain</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-back\"><canvas width=\"1400\" height=\"600\" id=\"fishtank\">\r\n");
      out.write("\t</div> \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper_login\">\r\n");
      out.write("\t\t<div class=\"container_login\">\r\n");
      out.write("\t\t\t<h1>Welcome to FishBang</h1>\r\n");
      out.write("\t\t\t<br><br><br><br><br>\r\n");
      out.write("\t\t\t<div class=\"div_button\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"login\" onclick=\"location.href='login.jsp'\">Login</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"div_button\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"signup\" onclick=\"location.href='signup.jsp'\">signup</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"div_button\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"start\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("'\">start</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("var FOLLOW_DISTANCE = 100;\r\n");
      out.write("\r\n");
      out.write("var Fish = function(id) {\r\n");
      out.write("\tthis.id = id;\r\n");
      out.write("\tthis.entourage = [];\r\n");
      out.write("\t// dx/yx is current speed, ox/oy is the previous one\r\n");
      out.write("\tthis.ox = this.dx = Math.random() - 0.5;\r\n");
      out.write("\tthis.oy = this.dy = Math.random() - 0.5;\r\n");
      out.write("\r\n");
      out.write("\tthis.x = canvas.width * Math.random();\r\n");
      out.write("\tthis.y = canvas.height * Math.random();\r\n");
      out.write("\r\n");
      out.write("\t// A couple of helper functions, the names should describe their purpose\r\n");
      out.write("\tFish.prototype.angleToClosestFish = function(otherFish) {\r\n");
      out.write("\t\totherFish = otherFish == null ? this.following : otherFish;\r\n");
      out.write("\t\tif (otherFish) {\r\n");
      out.write("\t\t\treturn Math.atan2(otherFish.y - this.y, otherFish.x - this.x);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\treturn Number.MAX_VALUE;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tFish.prototype.angleFromFishDirectionToClosestFish = function(otherFish) {\r\n");
      out.write("\t\totherFish = otherFish == null ? this.following : otherFish;\r\n");
      out.write("\t\tif (otherFish) {\r\n");
      out.write("\t\t\treturn Math.abs(deltaAngle(this.angle, this.angleToClosestFish(otherFish)));\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\treturn Number.MAX_VALUE;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tFish.prototype.angleDirectionDifference = function(otherFish) {\r\n");
      out.write("\t\totherFish = otherFish == null ? this.following : otherFish;\r\n");
      out.write("\r\n");
      out.write("\t\tif (otherFish) {\r\n");
      out.write("\t\t\tMath.abs(deltaAngle(this.angle, otherFish.angle));\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\treturn Number.MAX_VALUE;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t// Update the fish \"physics\"\r\n");
      out.write("\tFish.prototype.calc = function() {\r\n");
      out.write("\t\tthis.ox = this.dx;\r\n");
      out.write("\t\tthis.oy = this.dy;\r\n");
      out.write("\t\tvar MAX_SPEED = 1.1;\r\n");
      out.write("\t\tvar maxSpeed = MAX_SPEED;\r\n");
      out.write("\r\n");
      out.write("\t\t//Do I need to find another fish buddy?\r\n");
      out.write("\t\tif (this.following == null || py(this.x - this.following.x, this.y - this.following.y) > FOLLOW_DISTANCE) {\r\n");
      out.write("\t\t\tif (this.following != null) {\r\n");
      out.write("\t\t\t\tif (keyDown) affinityLine(this.following, this, \"white\");\r\n");
      out.write("\t\t\t\tthis.following.entourage.splice(this.following.entourage.indexOf(this));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tthis.following = null;\r\n");
      out.write("\r\n");
      out.write("\t\t\t//attract closer to other fish - find closest\r\n");
      out.write("\t\t\tvar closestDistance = Number.MAX_VALUE;\r\n");
      out.write("\t\t\tvar closestFish = null;\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (var i = 0; i < fishes.length; i++) {\r\n");
      out.write("\t\t\t\tvar fish = fishes[i];\r\n");
      out.write("\t\t\t\tif (fish != this) {\r\n");
      out.write("\t\t\t\t\tvar distance = py(this.x - fish.x, this.y - fish.y);\r\n");
      out.write("\t\t\t\t\t// Is it closer, within the max distance and within the sector that the fish can see?\r\n");
      out.write("\t\t\t\t\tif (distance < closestDistance && fish.following != this && distance < FOLLOW_DISTANCE && this.angleFromFishDirectionToClosestFish(fish) < Math.PI * 0.25) {\r\n");
      out.write("\t\t\t\t\t\tclosestDistance = distance;\r\n");
      out.write("\t\t\t\t\t\tclosestFish = fish;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (closestFish != null) {\r\n");
      out.write("\t\t\t\tthis.following = closestFish;\r\n");
      out.write("\t\t\t\tclosestFish.entourage.push(this);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Fish is following another\r\n");
      out.write("\t\tif (this.following != null) {\r\n");
      out.write("\t\t\t// Go closer to other fish\r\n");
      out.write("\t\t\tthis.followingDistance = py(this.x - this.following.x, this.y - this.following.y);\r\n");
      out.write("\t\t\tthis.distanceFactor = 1 - this.followingDistance / FOLLOW_DISTANCE;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// If going head on, just break a little before following\r\n");
      out.write("\t\t\tif (this.angleDirectionDifference() > (Math.PI * 0.9) && // On colliding angle?\r\n");
      out.write("\t\t\t\tthis.angleFromFishDirectionToClosestFish() < (Math.PI * 0.2)) { // In colliding sector?\r\n");
      out.write("\t\t\t\tthis.dx += this.following.x * 0.1;\r\n");
      out.write("\t\t\t\tthis.dy += this.following.y * 0.1;\r\n");
      out.write("\t\t\t\tif (keyDown) affinityLine(this.following, this, \"yellow\");\r\n");
      out.write("\t\t\t} else if (this.followingDistance > FOLLOW_DISTANCE * 0.3) { // Dont go closer if close\r\n");
      out.write("\t\t\t\tthis.dx += Math.cos(this.angleToClosestFish()) * (0.05 * this.distanceFactor);\r\n");
      out.write("\t\t\t\tthis.dy += Math.sin(this.angleToClosestFish()) * (0.05 * this.distanceFactor);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (keyDown) affinityLine(this.following, this, \"red\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Go closer to center, crashing into the canvas walls is just silly!\r\n");
      out.write("\t\tif (this.x < canvas.width * .1 || this.x > canvas.width * .9 || this.y < canvas.height * .2 || this.y > canvas.height * .8) {\r\n");
      out.write("\t\t\tthis.dx += (canvas.width / 2 - this.x) / 5000;\r\n");
      out.write("\t\t\tthis.dy += (canvas.height / 2 - this.y) / 5000;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Poor little fishies are scared of your cursor\r\n");
      out.write("\t\tif (py(this.x - cursor.x, this.y - cursor.y) < FOLLOW_DISTANCE * 0.75) {\r\n");
      out.write("\t\t\tthis.dx -= (cursor.x - this.x) / 500;\r\n");
      out.write("\t\t\tthis.dy -= (cursor.y - this.y) / 500;\r\n");
      out.write("\t\t\tmaxSpeed = 4;\r\n");
      out.write("\t\t\tif (keyDown) affinityLine(cursor, this, \"green\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// If following fish, try avoid going close to your siblings\r\n");
      out.write("\t\tif (this.following != null) {\r\n");
      out.write("\t\t\tfor (var i = 0; i < this.following.entourage.length; i++) {\r\n");
      out.write("\t\t\t\tvar siblingFish = this.following.entourage[i];\r\n");
      out.write("\t\t\t\tif (siblingFish !== this) {\r\n");
      out.write("\t\t\t\t\tif (py(this.x - siblingFish.x, this.y - siblingFish.y) < FOLLOW_DISTANCE * 0.2) {\r\n");
      out.write("\t\t\t\t\t\tif (keyDown) affinityLine(siblingFish, this, \"yellow\");\r\n");
      out.write("\t\t\t\t\t\tthis.dx -= (siblingFish.x - this.x) / 1000;\r\n");
      out.write("\t\t\t\t\t\tthis.dy -= (siblingFish.y - this.y) / 1000;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Calculate heading from new speed\r\n");
      out.write("\t\tthis.angle = Math.atan2(this.dy, this.dx);\r\n");
      out.write("\r\n");
      out.write("\t\t// Grab the speed from the vectors, and normalize it\r\n");
      out.write("\t\tvar speed = Math.max(0.1, Math.min(maxSpeed, py(this.dx, this.dy)));\r\n");
      out.write("\r\n");
      out.write("\t\t// Recreate speed vector from recombining angle of direction with normalized speed\r\n");
      out.write("\t\tthis.dx = Math.cos(this.angle) * (speed + speedBoost);\r\n");
      out.write("\t\tthis.dy = Math.sin(this.angle) * (speed + speedBoost);\r\n");
      out.write("\r\n");
      out.write("\t\t// Fish like to move it, move it!\r\n");
      out.write("\t\tthis.x += this.dx;\r\n");
      out.write("\t\tthis.y += this.dy;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ---------------------- FISH \"CLASS\" END -------------- */\r\n");
      out.write("\r\n");
      out.write("/* ---------------------- MAIN START -------------------- */\r\n");
      out.write("var canvas = document.getElementById('fishtank');\r\n");
      out.write("var context = canvas.getContext('2d');\r\n");
      out.write("\r\n");
      out.write("var fishes = [];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var speedBoostCountdown = 200,\r\n");
      out.write("\tspeedBoost = 0,\r\n");
      out.write("\tSPEED_BOOST = 2;\r\n");
      out.write("var fishBitmap = new Image()\r\n");
      out.write("fishBitmap.onload = function() {\r\n");
      out.write("\tupdate();\r\n");
      out.write("};\r\n");
      out.write("fishBitmap.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAFCAYAAABFA8wzAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyNpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOToxNSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjZEMjNEMUIyQjI1MTExRTM5QzhDQjczMjRDQUI3RkMwIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjZEMjNEMUIzQjI1MTExRTM5QzhDQjczMjRDQUI3RkMwIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6NkQyM0QxQjBCMjUxMTFFMzlDOENCNzMyNENBQjdGQzAiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6NkQyM0QxQjFCMjUxMTFFMzlDOENCNzMyNENBQjdGQzAiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz5h3qMOAAAAkUlEQVR42pyQsQrCQBBEPYkiQgSjRCvTpPf/f0OwtLIXlGAICZ5vyAhXWWTgcXCwj50NszEBCthCDitY+l8ZoIMWGniZIcY4CkLY8JQaKKH28BXOiehfZHqaHazhosEMDlDBx9tNyY1t75IdLVtMkLxdXec6Ufvxqzb32kVywyyp1pvWksZVO90QkTx7Ob4CDADGaiOnQPuXSgAAAABJRU5ErkJggg==';\r\n");
      out.write("\r\n");
      out.write("//Draw Circle\r\n");
      out.write("function draw(f) {\r\n");
      out.write("\tvar r = f.angle + Math.PI;\r\n");
      out.write("\r\n");
      out.write("\tcontext.translate(f.x, f.y);\r\n");
      out.write("\tcontext.rotate(r);\r\n");
      out.write("\r\n");
      out.write("\tvar w = 20;\r\n");
      out.write("\tvar acc = py(f.dx - f.ox, f.dy - f.oy) / 0.05;\r\n");
      out.write("\r\n");
      out.write("\t// If a fish does a \"flip\", make it less wide\r\n");
      out.write("\tif (acc > 1) {\r\n");
      out.write("\t\tw = 10 + 10 / acc;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tcontext.drawImage(fishBitmap, 0, 0, w, 6);\r\n");
      out.write("\tcontext.rotate(-r);\r\n");
      out.write("\tcontext.translate(-f.x, -f.y);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Pythagoras shortcut\r\n");
      out.write("function py(a, b) {\r\n");
      out.write("\treturn Math.sqrt(a * a + b * b);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//------------ USER INPUT START -------------\r\n");
      out.write("var cursor = {\r\n");
      out.write("\tx: 0,\r\n");
      out.write("\ty: 0\r\n");
      out.write("};\r\n");
      out.write("var cursorDown = false,\r\n");
      out.write("\tkeyDown = false;\r\n");
      out.write("\r\n");
      out.write("document.onmousemove = function(e) {\r\n");
      out.write("\tcursor.x = e.pageX - (window.innerWidth / 2 - canvas.width / 2);\r\n");
      out.write("\tcursor.y = e.pageY - (window.innerHeight / 2 - canvas.height / 2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.onmouseout = function(e) { //Out of screen is not a valid pos\r\n");
      out.write("\tcursor.y = cursor.x = Number.MAX_VALUE;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.onmousedown = function() {\r\n");
      out.write("\tactivateSpeedBoost();\r\n");
      out.write("\tcursorDown = true;\r\n");
      out.write("}\r\n");
      out.write("document.onmouseup = function() {\r\n");
      out.write("\tcursorDown = false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.onkeydown = function() {\r\n");
      out.write("\tkeyDown = true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.onkeyup = function() {\r\n");
      out.write("\t\tkeyDown = false;\r\n");
      out.write("\t}\r\n");
      out.write("\t//------------ USER INPUT STOP -------------\r\n");
      out.write("\r\n");
      out.write("function deltaAngle(f, o) { //Find the shortest angle between two\r\n");
      out.write("\tvar r = f - o;\r\n");
      out.write("\treturn Math.atan2(Math.sin(r), Math.cos(r));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function affinityLine(f, o, c) { //Draw a line with pretty gradient\r\n");
      out.write("\tvar grad = context.createLinearGradient(f.x, f.y, o.x, o.y);\r\n");
      out.write("\tgrad.addColorStop(0, c);\r\n");
      out.write("\tgrad.addColorStop(1, \"black\");\r\n");
      out.write("\r\n");
      out.write("\tcontext.strokeStyle = grad;\r\n");
      out.write("\tcontext.beginPath();\r\n");
      out.write("\tcontext.moveTo(f.x, f.y);\r\n");
      out.write("\tcontext.lineTo(o.x, o.y);\r\n");
      out.write("\tcontext.stroke();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function activateSpeedBoost() {\r\n");
      out.write("\tspeedBoostCountdown = 400 + Math.round(400 * Math.random());\r\n");
      out.write("\tspeedBoost = SPEED_BOOST;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Update and draw all of them\r\n");
      out.write("function update() {\r\n");
      out.write("\t\tif (fishes.length < 500) {\r\n");
      out.write("\t\t\tfishes.push(new Fish(fishes.length));\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (!cursorDown) {\r\n");
      out.write("\t\t\t//clear the canvas\r\n");
      out.write("\t\t\tcanvas.width = canvas.width; //Try commenting this line :-)\r\n");
      out.write("\r\n");
      out.write("\t\t\t//Update and draw fish\r\n");
      out.write("\t\t\tfor (var i = 0; i < fishes.length; i++) {\r\n");
      out.write("\t\t\t\tvar fish = fishes[i];\r\n");
      out.write("\t\t\t\tfish.calc();\r\n");
      out.write("\t\t\t\tdraw(fish);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tspeedBoostCountdown--;\r\n");
      out.write("\t\tif (speedBoostCountdown < 0) {\r\n");
      out.write("\t\t\tactivateSpeedBoost();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (speedBoost > 0) {\r\n");
      out.write("\t\t\tspeedBoost -= SPEED_BOOST / 80; //Reduce speed bost fast!\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tspeedBoost = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\trequestAnimationFrame(update);\r\n");
      out.write("\t}\r\n");
      out.write("\t/* ---------------------- MAIN END ----------------------- */\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /jsp/projectMain.jsp(10,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/project_login.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /jsp/projectMain.jsp(12,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/css/project_background.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /jsp/projectMain.jsp(39,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/jsp/projectUi.jsp");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
